/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ProjectUAS_Alpro2;

import java.awt.CardLayout;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author Hanif
 */
public class login extends javax.swing.JFrame {
    // deklarasi
    Connection conn = null;
    Statement stat;
    PreparedStatement pst = null;
    ResultSet rs;
    String sql;
    
    koneksi DB = new koneksi();
    
    public login() {
        initComponents();
        
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dasar = new javax.swing.JPanel();
        pnlDash = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnSU = new javax.swing.JButton();
        btLogin = new javax.swing.JButton();
        btExitProgram = new javax.swing.JButton();
        pnlLogin = new javax.swing.JPanel();
        txtNameLog = new javax.swing.JTextField();
        txtPassLog = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        btStart = new javax.swing.JButton();
        btGuest1 = new javax.swing.JButton();
        btBack = new javax.swing.JButton();
        pnlSignUp = new javax.swing.JPanel();
        txtUsername = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtNoTelp = new javax.swing.JTextField();
        txtPassSU = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        btSignUp = new javax.swing.JButton();
        btHaveAccount = new javax.swing.JButton();
        btGuest2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        dasar.setBackground(new java.awt.Color(255, 255, 255));
        dasar.setLayout(new java.awt.CardLayout());

        pnlDash.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon("D:\\Pribadi\\Picture\\PROJEK UAS ALPRO 2 REG Penyambut 2-01.png")); // NOI18N
        pnlDash.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        btnSU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSUActionPerformed(evt);
            }
        });
        pnlDash.add(btnSU, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 690, 180, 70));

        btLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLoginActionPerformed(evt);
            }
        });
        pnlDash.add(btLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 690, 190, 70));

        btExitProgram.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExitProgramActionPerformed(evt);
            }
        });
        pnlDash.add(btExitProgram, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 790, 180, 80));

        dasar.add(pnlDash, "dash");

        pnlLogin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtNameLog.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        txtNameLog.setBorder(null);
        pnlLogin.add(txtNameLog, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 470, 520, 50));

        txtPassLog.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        txtPassLog.setBorder(null);
        pnlLogin.add(txtPassLog, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 570, 520, 60));

        jLabel2.setIcon(new javax.swing.ImageIcon("D:\\Pribadi\\Picture\\PROJEK UAS ALPRO 2 REG Login-01.png")); // NOI18N
        pnlLogin.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1520, 1080));

        btStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btStartActionPerformed(evt);
            }
        });
        pnlLogin.add(btStart, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 670, 180, 70));

        btGuest1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGuest1ActionPerformed(evt);
            }
        });
        pnlLogin.add(btGuest1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 770, 540, 70));

        btBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBackActionPerformed(evt);
            }
        });
        pnlLogin.add(btBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 670, 170, 70));

        dasar.add(pnlLogin, "login");

        pnlSignUp.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtUsername.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        txtUsername.setBorder(null);
        pnlSignUp.add(txtUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(864, 306, 550, 60));

        txtEmail.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        txtEmail.setBorder(null);
        pnlSignUp.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(864, 406, 550, 60));

        txtNoTelp.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        txtNoTelp.setBorder(null);
        pnlSignUp.add(txtNoTelp, new org.netbeans.lib.awtextra.AbsoluteConstraints(864, 506, 550, 60));

        txtPassSU.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        txtPassSU.setBorder(null);
        pnlSignUp.add(txtPassSU, new org.netbeans.lib.awtextra.AbsoluteConstraints(856, 610, 560, 50));

        jLabel5.setIcon(new javax.swing.ImageIcon("D:\\Pribadi\\Picture\\Daftar-01.png")); // NOI18N
        pnlSignUp.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 0, 1520, 1080));

        btSignUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSignUpActionPerformed(evt);
            }
        });
        pnlSignUp.add(btSignUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 700, 180, 70));

        btHaveAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btHaveAccountActionPerformed(evt);
            }
        });
        pnlSignUp.add(btHaveAccount, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 789, 440, 40));

        btGuest2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGuest2ActionPerformed(evt);
            }
        });
        pnlSignUp.add(btGuest2, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 850, 570, 70));

        dasar.add(pnlSignUp, "signup");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dasar, javax.swing.GroupLayout.PREFERRED_SIZE, 1522, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dasar, javax.swing.GroupLayout.PREFERRED_SIZE, 1083, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSUActionPerformed
        CardLayout cLayout = (CardLayout) dasar.getLayout();
        cLayout.show(dasar, "signup");
    }//GEN-LAST:event_btnSUActionPerformed

    private void btLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLoginActionPerformed
        CardLayout cLayout = (CardLayout) dasar.getLayout();
        cLayout.show(dasar, "login");
    }//GEN-LAST:event_btLoginActionPerformed

    private void btStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btStartActionPerformed
        try{
            DB.koneksi();
            conn = DB.con;
            stat = DB.stn;
            sql = "SELECT * FROM admin WHERE password ='" + txtPassLog.getText()
                    + "' OR username ='" + txtNameLog.getText() + "' OR"
                    + " email ='" + txtNameLog.getText() + "'";
            rs = stat.executeQuery(sql);
            if (rs.next()) {
                String tes = "";
                if ( ( txtNameLog.getText().equals(rs.getString("username")) ||
                        txtNameLog.getText().equals(rs.getString("email")) ) && 
                        txtPassLog.getText().equals (rs.getString ("password"))){
                    
                    JOptionPane.showMessageDialog(null, "Login Anda Telah Berhasil,"
                            + " Selamat Bermain :)");
                    
                    game secondGUI = new game();
                    secondGUI.setVisible(true);
                    this.dispose();
                    
                    txtNameLog.setText("");
                    txtPassLog.setText("");
                } else{
                    JOptionPane.showMessageDialog(null, "maaf, kombinasi username "
                            + "dan password salah");
                }
            } else {
                if (txtNameLog.getText() == ""){
                    JOptionPane.showMessageDialog(null, "Mohon isi field username");
                } else if (txtPassLog.getText() == ""){
                    JOptionPane.showMessageDialog(null, "Mohon isi field password");
                } else if (txtPassLog.getText() == "" && txtNameLog.getText() == ""){
                    JOptionPane.showMessageDialog(null, "Mohon isi field username & password");
                } else{
                    JOptionPane.showMessageDialog(null, "rs.next() tidak tersambung");
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_btStartActionPerformed

    private void btGuest1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGuest1ActionPerformed
        JOptionPane.showMessageDialog(null, "Login Anda Telah Berhasil, "
                + "Selemat Bermain !!!");
        
        game secondGUI = new game();
        secondGUI.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btGuest1ActionPerformed

    private void btGuest2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGuest2ActionPerformed
        JOptionPane.showMessageDialog(null, "Login Anda Telah Berhasil, "
                + "Selemat Bermain !!!");
        
        game secondGUI = new game();
        secondGUI.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btGuest2ActionPerformed

    private void btHaveAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btHaveAccountActionPerformed
        CardLayout cLayout = (CardLayout) dasar.getLayout();
        cLayout.show(dasar, "login");
    }//GEN-LAST:event_btHaveAccountActionPerformed

    private void btBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBackActionPerformed
        CardLayout cLayout = (CardLayout) dasar.getLayout();
        cLayout.show(dasar, "dash");
    }//GEN-LAST:event_btBackActionPerformed

    private void btSignUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSignUpActionPerformed
        try {
            DB.koneksi();
            conn = DB.con;
            stat = DB.stn;
            
            sql ="INSERT INTO admin (username, password, no_telp, email) "
                    + "VALUES (?, ?, ?, ?)";
            pst = conn.prepareStatement(sql);
            pst.setString(1, txtUsername.getText());
            pst.setString(2, txtPassSU.getText());
            pst.setString(3, txtNoTelp.getText());
            pst.setString(4, txtEmail.getText());
            pst.executeUpdate();
            
            JOptionPane.showMessageDialog(null, "Penambahan Data Peserta Berhasil");
            
            txtEmail.setText("");
            txtNoTelp.setText("");
            txtUsername.setText("");
            txtPassSU.setText("");
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }     
    }//GEN-LAST:event_btSignUpActionPerformed

    private void btExitProgramActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExitProgramActionPerformed
        int response = JOptionPane.showConfirmDialog(null,"Do you want to leave"
                + " application ?","Confirmation",
                JOptionPane.YES_OPTION,JOptionPane.QUESTION_MESSAGE);
        switch (response) {
            case JOptionPane.YES_OPTION:
                System.exit(0);   
        }
    }//GEN-LAST:event_btExitProgramActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btBack;
    private javax.swing.JButton btExitProgram;
    private javax.swing.JButton btGuest1;
    private javax.swing.JButton btGuest2;
    private javax.swing.JButton btHaveAccount;
    private javax.swing.JButton btLogin;
    private javax.swing.JButton btSignUp;
    private javax.swing.JButton btStart;
    private javax.swing.JButton btnSU;
    private javax.swing.JPanel dasar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel pnlDash;
    private javax.swing.JPanel pnlLogin;
    private javax.swing.JPanel pnlSignUp;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtNameLog;
    private javax.swing.JTextField txtNoTelp;
    private javax.swing.JPasswordField txtPassLog;
    private javax.swing.JPasswordField txtPassSU;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
